// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJFkCng-MwnVzV42C68-plWElnDfwKYw',
    appId: '1:297136857095:web:1e0813d7b509dc55f0caa2',
    messagingSenderId: '297136857095',
    projectId: 'fittrack-dbea3',
    authDomain: 'fittrack-dbea3.firebaseapp.com',
    storageBucket: 'fittrack-dbea3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk0Va3RYJMUQXI0QRDPt06YdKrB5vaxdk',
    appId: '1:297136857095:android:0a7803d6cd61f52ef0caa2',
    messagingSenderId: '297136857095',
    projectId: 'fittrack-dbea3',
    storageBucket: 'fittrack-dbea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCg6Lp-wlvkixZaMNlxAviWLLynfuTM0',
    appId: '1:297136857095:ios:13cc1d50d0c88bdaf0caa2',
    messagingSenderId: '297136857095',
    projectId: 'fittrack-dbea3',
    storageBucket: 'fittrack-dbea3.appspot.com',
    iosBundleId: 'com.example.flutterProyectoFitness',
  );
}
